Song.create(title: "Punta Icotea", videoref: "4rD12g6h_ww", artist: "Gran Coquivacoa", length: 218)
Song.create(title: "Djanfa", videoref: "gTeiw0I5ExA", artist: "Amadou et Mariam", length: 254)
Song.create(title: "Ripples", videoref: "gJa9gEUa0To", artist: "Genesis", length: 333)
Song.create(title: "Que he sacado con quererte", videoref: "6fFeqqaOsTU", artist: "Mercedes Sosa", length: 235)
Song.create(title: "Rock and Roll Soniye", videoref: "7nDKFPWbJMU", artist: "Abhishek Bachchan", length: 326)
Song.create(title: "Como te voy a olvidar", videoref: "nxXvOEPsE0s", artist: "Los Angeles Azules", length: 269)
Song.create(title: "No puedo verme más", videoref: "3iy12vr0vfQ", artist: "La máquina de hacer pájaros", length: 255)
Song.create(title: "Arrabal Amargo", videoref: "EisMUedFtso", artist: "Carlos Gardel", length: 155)
Song.create(title: "Las Gaitas de Joselo", videoref: "dHyxOlPITGc", artist: ".Joselo", length: 1915)
Song.create(title: "La Gaita de Las Locas 4", videoref: "fvnV4BNzD9k", artist: "Simón Díaz & Hugo Blanco", length: 614)
Song.create(title: "Decí por qué no querés", videoref: "-t-6XY2Dqlw", artist: "Chaqueño Palavecino", length: 166)
Songtag.create(song_id: 1, tag_id: 2)
Songtag.create(song_id: 1, tag_id: 3)
Songtag.create(song_id: 1, tag_id: 10)
Songtag.create(song_id: 2, tag_id: 8)
Songtag.create(song_id: 4, tag_id: 4)
Songtag.create(song_id: 5, tag_id: 1)
Songtag.create(song_id: 5, tag_id: 5)
Songtag.create(song_id: 6, tag_id: 6)
Songtag.create(song_id: 7, tag_id: 4)
Songtag.create(song_id: 7, tag_id: 8)
Songtag.create(song_id: 8, tag_id: 4)
Songtag.create(song_id: 8, tag_id: 9)
Songtag.create(song_id: 9, tag_id: 2)
Songtag.create(song_id: 9, tag_id: 3)
Songtag.create(song_id: 9, tag_id: 10)
Songtag.create(song_id: 10, tag_id: 2)
Songtag.create(song_id: 10, tag_id: 3)
Songtag.create(song_id: 10, tag_id: 10)
Songtag.create(song_id: 11, tag_id: 4)
Tag.create(tagname: "India", current: "2011")
Tag.create(tagname: "Zulia", current: "2001")
Tag.create(tagname: "Venezuela", current: "1000")
Tag.create(tagname: "Argentina", current: "2009")
Tag.create(tagname: "Bollywood", current: "2016")
Tag.create(tagname: "Cumbia", current: "2000")
Tag.create(tagname: "Africa", current: "2009")
Tag.create(tagname: "Rock argentino", current: "2008")
Tag.create(tagname: "Tango", current: "2000")
Tag.create(tagname: "Gaita zuliana", current: "1976")
User.create(username: "pinchox", useravatar: "Shivaji")
User.create(username: "kinol", useravatar: "Nili Nili")
User.create(username: "Samarjit Talwar", useravatar: "Sexy Sam")
User.create(username: "Butch Cassidy", useravatar: "Sunshine")
User.create(username: "Argento", useravatar: "Patoruzú")
Usertag.create(validated: "LinkTag1User5", user_id: 5, tag_id: 1)
Usertag.create(validated: "LinkTag3User3", user_id: 3, tag_id: 3)
Usertag.create(validated: "LinkTag2User1", user_id: 1, tag_id: 2)
Usertag.create(validated: "LinkTag1User1", user_id: 1, tag_id: 1)
Usertag.create(validated: "LinkTag5User4", user_id: 4, tag_id: 5)
Usertag.create(validated: "LinkTag5User2", user_id: 2, tag_id: 5)
Usertag.create(validated: "User4Tag2", user_id: 4, tag_id: 2)
Usertag.create(validated: "PinchoGaitaLocas", user_id: 1, tag_id: 11)